### ISSUE TITLE
AppendAny and AppendVariable for Int values not producing correct value

### ISSUE THREAD

**Issue by chrisbeardy** [bengeisler/TcLog#14]
I am having an issue appending int values using AppendAny. I think perhaps the pointer values are not lining up?

For example -18000 (is) is appearing as 115.

**Comment by bengeisler** [comment]
Hi, thanks for bringing this up! I'll look into it.

**Comment by bengeisler** [comment]
The problem seems to be with the `ANY_TO_STRING` function from Beckhoff that doesn't show the expected behavior. Surprisingly, all information about it on the web is gone :smile:
I already had a custom `AnyToString` function for other data types, it seems that I have to use it for all data types.

**Comment by bengeisler** [comment]
That was a really good catch 👍 
Please use the updated library version `0.3.1` on Twinpack or under [releases](https://github.com/bengeisler/TcLog/releases/tag/v0.3.1).
