### ISSUE TITLE
Twinpack registry

### ISSUE THREAD

**Issue by iadonkey** [bengeisler/TcLog#15]
Hi!
I would like to put your repository on the twinpack registry, which we just developed: https://github.com/Zeugwerk/Twinpack-Registry

This will automatically check your repository for new releases and if there is one that is not available on Twinpack yet, it is uploaded to Twinpack. It is only required to have the .library file as an asset in the release, which you do anyway. In the next release we will even have a feature that directly downloads libraries from the GitHub assets and will do a fingerprint check to make sure that the library was not modified after publishing.

No other interaction is required for publishing to Twinpack as soon as a repository is on the list. As Twinpack itself, the registry is open source and available here https://github.com/Zeugwerk/Twinpack/tree/main/TwinpackRegistry

Are you ok with this? If you like this initiative please spread the word, we want to get some momentum in the TwinCAT community by this

**Comment by bengeisler** [comment]
Hi! 
You're doing cool stuff for the community 👍 
Sure I'm ok with it! Thanks for reaching out!
