### ISSUE TITLE
Question: how to log multiple Boolean transitions within one FB.

### ISSUE THREAD

**Issue by paulbarron85** [bengeisler/TcLog#19]
How should one log multiple Boolean signals in the same FB? Is it ok to use the same instance or do you require a new FB for each thing you want to log. Specifically, I'm looking at the TcLogTrig. For example, can I do the following:
```
FUNCTION_BLOCK FB_DigitalInputLogger
VAR_INPUT
        input1 : BOOL;
        input2 : BOOL;
	fbCoreLog : REFERENCE TO TcLogCore;
END_VAR
VAR
	fbTcLogTrig : TcLogTrig;
END_VAR

fbTcLogTrig.SetLogger(fbCoreLog);
fbTcLogTrig
	.OnRisingEdge(input1)
	.Information('Input 1 is TRUE');
fbTcLogTrig
	.OnFallingEdge(input1)
	.Information('Input 2 is FALSE');
	
fbTcLogTrig
	.OnRisingEdge(input2)
	.Information('Input 2 is TRUE');
fbTcLogTrig
	.OnFallingEdge(input2)
	.Information('Input 2 FALSE');
```

**Comment by bengeisler** [comment]
You have two options:
- Use the standard logger and log `OnCondition`. You have to catch the rising edges yourself with `R_TRIG` and pass the result into the logger
- Use a single instance of `FB_LogTRIG` for each of your variables
