### ISSUE TITLE
ErrorCodes' is no component of 'TCLOG

### ISSUE THREAD

**Issue by zhangalps** [bengeisler/TcLog#20]
this is my code

```
PROGRAM MAIN
VAR
	tcLog:TcLogCore(bufferSize:= 1000);
END_VAR
```

**Comment by bengeisler** [comment]
Please provide more details to this issue.

**Comment by zhangalps** [comment]
Install tclog version is 0.4 and TC31-FULL-Setup.3.1.4024.54.exe on my device，Does it have anything to do with the version?

**Comment by zhangalps** [comment]
I tried to roll back the Twincat version to TC31-FULL-Setup.3.1.4024.40.exe and it run ok
