### ISSUE TITLE
Many error messages with TwinCat 4024.55

### ISSUE THREAD

**Issue by urbanmc89** [bengeisler/TcLog#22]
We had to change the TwinCat from version 4024.32 to 4024.55 due to driver problems on a new Beckhoff computer. Since the change to the 55 version, I can no longer compile the program as long as TcLog is active. There are problems recognizing the contents of the library. 
If I switch back to 4024.32 on the same PC, everything works again.

There will then be 120 error messages. Here are a few as an example:

- Expression of type 'BOOL' expected in this place
- Functionblock 'TcLog' must be instantiated to be accessed
- Unknown type: 'TcLog.ErrorCodes.ClosingFileFailed'
- Unknown type: 'TcLog.ErrorCodes.EnumeratingFilesInSpecifiedDirectoryFailed'
- Unknown type: 'TcLog.LogLevels.Fatal'
- Unknown type: 'TcLog.LogLevels.Error'
- Unknown type: 'TcLog.LogLevels.Warning'
- Unknown type: 'TcLog.LogLevels.Information'
- Unknown type: 'TcLog.LogLevels.Debug'

**Comment by seehma** [comment]
How are you referencing TcLog? can you show us the Properties Window?
Did you try to install it via Twinpack or did you install it manually?

**Comment by Poor-Tony** [comment]
I ran into the same issue, also with 4024.55. Had the exact same 120 error messages. Updated to 4024.56, didn't help. Went back to 4024.53, that solved it.
I installed the library manually.

**Comment by bengeisler** [comment]
Hi!

Thanks for bringing this up. I'll look into it. 

> How are you referencing TcLog? can you show us the Properties Window? Did you try to install it via Twinpack or did you install it manually?

Could you provide information to this question?

And did you check [this guide](https://github.com/bengeisler/TcLog/issues/21#issuecomment-1998988138) in #21?

**Comment by seehma** [comment]
I think its the same problem as in the other issue. 
Just go on the library and then right click on it -> open Properties.
Then in the properties window check if "Qualified access only" is set to TRUE;
![grafik](https://github.com/bengeisler/TcLog/assets/7335330/56f05c59-25c0-438c-9a9f-975ed0368a31)
Also make sure that you access all types and objects from the TcLog library with the right namespace...

**Comment by bengeisler** [comment]
The [latest release](https://github.com/bengeisler/TcLog/releases/tag/v0.5.0) fixed this by providing a different namespace. You should be able to use it in 4024.55 without any changes.

**Comment by urbanmc89** [comment]
Sorry for my late response.
Thank you for finding and fixing the problem so quickly. 
Best regards 
Björn
