### ISSUE TITLE
Contributing guide

### ISSUE THREAD

**Issue by mihaiginta** [bengeisler/TcLog#3]
Hello, I have started using this library and I have encountered small issues, that I might try to fix. What is the desired contributing strategy?

Best regards,
Mihai

**Comment by bengeisler** [comment]
Hi Mihai,
thanks for reaching out! 
I‘d suggest you either open an issue for each issue you found, we discuss it, and I fix it. 

Alternatively, you can open a pull request that includes unit tests to reproduce the issues and optionally also a bug fix. Then I‘ll check and merge it. 

Cheers
Benedikt

**Comment by bengeisler** [comment]
A [contributing guide](https://github.com/bengeisler/TcLog/blob/main/CONTRIBUTING.md) is now available.
