### ISSUE TITLE
Twinpack library

### ISSUE THREAD

**Issue by runtimevic** [bengeisler/TcLog#5]
Hello @bengeisler 
It would be great if you included the library in TwinPack,
I'll give you the link:
https://github.com/Zeugwerk/Twinpack

**Comment by bengeisler** [comment]
I‘m currently working on a performance improvement of the library. Once that is done I‘ll share it on Twinpack. Thanks for reaching out!

**Comment by bengeisler** [comment]
The latest release including the performance upgrade is now on TwinPack.
